FROM python:3.10
WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc g++ libgomp1 libgl1 libsm6 libxext6 \
    libxrender-dev libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# docker build -f Dockerfile.base -t inference-dependencies:latest ./models-inference